[2021-09-08 10:44:01,000] ERROR [test_2: test_info.py, 39] 你的用例2报错啦
[2021-09-08 10:44:01,002] INFO [test_2: test_info.py, 42] 运行完辣
